insert into public.catalog_pages (
  universe_id,
  code,
  title,
  seo_title,
  meta_description,
  intro_md,
  how_it_works_md,
  description_json,
  faq_json,
  is_published
)
values
  (
    7671049560,
    'the-forge-ores',
    'All Ores in The Forge',
    'All Ores in The Forge',
    'Browse every ore in The Forge with drop chances, multipliers, and regions.',
    'Browse every ore in The Forge with drop chances, multipliers, and regions.',
    '',
    '{}'::jsonb,
    '[]'::jsonb,
    false
  ),
  (
    7671049560,
    'the-forge-weapons',
    'All Weapons in The Forge',
    'All Weapons in The Forge',
    'Compare every forgeable weapon in The Forge grouped by class.',
    'Compare every forgeable weapon in The Forge grouped by class.',
    '',
    '{}'::jsonb,
    '[]'::jsonb,
    false
  ),
  (
    7671049560,
    'the-forge-armors',
    'All Armors in The Forge',
    'All Armors in The Forge',
    'See every armor piece in The Forge, grouped by armor class.',
    'See every armor piece in The Forge, grouped by armor class.',
    '',
    '{}'::jsonb,
    '[]'::jsonb,
    false
  ),
  (
    7671049560,
    'the-forge-pickaxes',
    'All Pickaxes in The Forge',
    'All Pickaxes in The Forge',
    'Explore every pickaxe in The Forge with power, speed, and luck stats.',
    'Explore every pickaxe in The Forge with power, speed, and luck stats.',
    '',
    '{}'::jsonb,
    '[]'::jsonb,
    false
  ),
  (
    7671049560,
    'the-forge-runes',
    'All Runes in The Forge',
    'All Runes in The Forge',
    'All The Forge runes with elements, rarities, and effects.',
    'All The Forge runes with elements, rarities, and effects.',
    '',
    '{}'::jsonb,
    '[]'::jsonb,
    false
  ),
  (
    7671049560,
    'the-forge-races',
    'All Races in The Forge',
    'All Races in The Forge',
    'Every The Forge race with tiers, roll chances, and stat bonuses.',
    'Every The Forge race with tiers, roll chances, and stat bonuses.',
    '',
    '{}'::jsonb,
    '[]'::jsonb,
    false
  ),
  (
    7671049560,
    'the-forge-essences',
    'All Essences in The Forge',
    'All Essences in The Forge',
    'All The Forge essences organized by tier.',
    'All The Forge essences organized by tier.',
    '',
    '{}'::jsonb,
    '[]'::jsonb,
    false
  ),
  (
    7671049560,
    'the-forge-totems',
    'All Totems in The Forge',
    'All Totems in The Forge',
    'Every The Forge totem with cost and effect details.',
    'Every The Forge totem with cost and effect details.',
    '',
    '{}'::jsonb,
    '[]'::jsonb,
    false
  ),
  (
    7671049560,
    'the-forge-potions',
    'All Potions in The Forge',
    'All Potions in The Forge',
    'Every The Forge potion with cost and effect details.',
    'Every The Forge potion with cost and effect details.',
    '',
    '{}'::jsonb,
    '[]'::jsonb,
    false
  ),
  (
    7671049560,
    'the-forge-enemies',
    'All Enemies in The Forge',
    'All Enemies in The Forge',
    'The Forge enemy list with stats, gold, and experience rewards.',
    'The Forge enemy list with stats, gold, and experience rewards.',
    '',
    '{}'::jsonb,
    '[]'::jsonb,
    false
  ),
  (
    7671049560,
    'the-forge-npcs',
    'All NPCs in The Forge',
    'All NPCs in The Forge',
    'The Forge NPC roster and their roles.',
    'The Forge NPC roster and their roles.',
    '',
    '{}'::jsonb,
    '[]'::jsonb,
    false
  ),
  (
    7671049560,
    'the-forge-quests',
    'All Quests in The Forge',
    'All Quests in The Forge',
    'Track The Forge quests by world, NPC, and listed objectives.',
    'Track The Forge quests by world, NPC, and listed objectives.',
    '',
    '{}'::jsonb,
    '[]'::jsonb,
    false
  ),
  (
    7671049560,
    'the-forge-skills',
    'All Skills in The Forge',
    'All Skills in The Forge',
    'Compare The Forge skill boosts and the achievements used to unlock them.',
    'Compare The Forge skill boosts and the achievements used to unlock them.',
    '',
    '{}'::jsonb,
    '[]'::jsonb,
    false
  ),
  (
    7671049560,
    'the-forge-blueprints',
    'All Blueprints in The Forge',
    'All Blueprints in The Forge',
    'See The Forge blueprints, where they come from, and whether they are available.',
    'See The Forge blueprints, where they come from, and whether they are available.',
    '',
    '{}'::jsonb,
    '[]'::jsonb,
    false
  ),
  (
    7671049560,
    'the-forge-locations',
    'All Locations in The Forge',
    'All Locations in The Forge',
    'The Forge locations organized by area and type.',
    'The Forge locations organized by area and type.',
    '',
    '{}'::jsonb,
    '[]'::jsonb,
    false
  )
on conflict (code) do update
set
  universe_id = excluded.universe_id,
  title = excluded.title,
  seo_title = excluded.seo_title,
  meta_description = excluded.meta_description,
  intro_md = excluded.intro_md,
  how_it_works_md = excluded.how_it_works_md,
  description_json = excluded.description_json,
  faq_json = excluded.faq_json,
  is_published = excluded.is_published;
