"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { beaconPlan, buildingPlan, circleGrid, circleSvg, furnacePlan, portalCoordinates, storagePlan, triangulate, xpPlan } from "@/lib/minecraft-tools/calculations";
import { inEdition, type Edition, type ToolRules } from "@/lib/minecraft-tools/types";
import { Choice, Download, Fields, format, Metrics, NumberField, Panel, pretty, readNumber as n, Result, calculate } from "./ToolControls";

export function NetherTool() {
  const [x, sx] = useState("800"), [y, sy] = useState("64"), [z, sz] = useState("-400"), [direction, sd] = useState("to-nether");
  const result = calculate(() => portalCoordinates(n(x), n(y), n(z), direction as "to-nether" | "to-overworld"));
  return <Panel><Fields><Choice label="Travel direction" value={direction} onChange={sd} options={[{ value: "to-nether", label: "Overworld to Nether" }, { value: "to-overworld", label: "Nether to Overworld" }]} /><NumberField label="X coordinate" value={x} onChange={sx} step={0.01} /><NumberField label="Y coordinate" value={y} onChange={sy} step={0.01} /><NumberField label="Z coordinate" value={z} onChange={sz} step={0.01} /></Fields><Result error={result.error}>{result.value && <Metrics rows={[["Target X", result.value.x], ["Target Z", result.value.z], ["Target block X", result.value.blockX], ["Target block Z", result.value.blockZ], ["Original Y", result.value.y]]} />}</Result><p className="text-sm text-muted">X and Z scale by eight. Y does not scale, but choose a safe height in the destination dimension. Existing portals, height, and the portal search range can change the actual link. Negative block positions round down.</p></Panel>;
}
export function StorageTool({ rules, edition }: { rules: ToolRules; edition: Edition }) {
  const items = inEdition(rules.items ?? [], edition);
  const [itemId, si] = useState(items.find(item => item.id === "cobblestone")?.id ?? items[0]?.id ?? ""), [quantity, sq] = useState("1728"), [slots, ss] = useState("27");
  const item = items.find(row => row.id === itemId) ?? items[0];
  const result = calculate(() => { if (!item) throw new Error("No verified item stack data exists for this edition."); return storagePlan(n(quantity), item, n(slots)); });
  return <Panel><Fields><Choice label="Item" value={item?.id ?? ""} onChange={si} options={items.map(row => ({ value: row.id, label: `${row.name} (${row.stackSize} per stack)` }))} /><NumberField label="Item quantity" value={quantity} onChange={sq} min={0} /><Choice label="Container" value={slots} onChange={ss} options={[{ value: "27", label: "Chest or shulker box (27 slots)" }, { value: "54", label: "Double chest (54 slots)" }, { value: "9", label: "Dispenser (9 slots)" }, { value: "5", label: "Hopper (5 slots)" }]} /></Fields><Result error={result.error}>{result.value && <Metrics rows={[["Full stacks", result.value.fullStacks], ["Items in the partial stack", result.value.remainder], ["Occupied slots", result.value.occupiedSlots], ["Containers required", result.value.containers], ["Empty slots in those containers", result.value.freeSlots]]} />}</Result><p className="text-sm text-muted">The selected item's stack limit controls the calculation. Containers are empty and hold only this item. Filled containers and bundled contents are outside this estimate.</p></Panel>;
}
export function FurnaceTool({ rules, edition }: { rules: ToolRules; edition: Edition }) {
  const fuels = inEdition(rules.fuels ?? [], edition);
  const [fuelId, sf] = useState(fuels.find(f => f.id === "coal")?.id ?? fuels[0]?.id ?? ""), [count, sc] = useState("64"), [station, ss] = useState("furnace"), [stations, sstations] = useState("1");
  const fuel = fuels.find(row => row.id === fuelId) ?? fuels[0];
  const processing = inEdition(rules.processing ?? [], edition).filter(row => row.station === station);
  const [processId, sp] = useState("");
  const process = processing.find(row => row.id === processId) ?? processing[0];
  const result = calculate(() => { if (!fuel) throw new Error("No fuel data exists for this edition."); if (!process) throw new Error("Choose a processable item for this station."); return furnacePlan(n(count), fuel, station as "furnace" | "smoker" | "blast-furnace", n(stations)); });
  return <Panel><Fields><Choice label="Fuel" value={fuel?.id ?? ""} onChange={sf} options={fuels.map(row => ({ value: row.id, label: row.name }))} /><NumberField label="Items to process" value={count} onChange={sc} min={0} /><Choice label="Station" value={station} onChange={value => { ss(value); sp(""); }} options={[{ value: "furnace", label: "Furnace" }, { value: "blast-furnace", label: "Blast furnace (ores and metal equipment)" }, { value: "smoker", label: "Smoker (food)" }]} /><Choice label="Item to process" value={process?.id ?? ""} onChange={sp} options={processing.map(row => ({ value: row.id, label: row.name }))} /><NumberField label="Parallel stations" value={stations} onChange={sstations} min={1} max={256} /></Fields><Result error={result.error}>{result.value && <Metrics rows={[["Fuel items", result.value.fuelCount], ["Processing capacity per fuel", result.value.capacityPerFuel], ["Unused burning capacity", result.value.unusedCapacity], ["Processing time in seconds", result.value.seconds], ["Stations used", result.value.stationsUsed], ...(fuel?.remainder ? [[`Returned ${pretty(fuel.remainder)}`, result.value.remainderContainers] as [string, number]] : [])]} />}</Result><p className="text-sm text-muted">Use items the selected station can process. This estimates uninterrupted vanilla processing in empty stations. Parallel stations receive balanced batches; each burns its own fuel. Unused burning time cannot be stored after you stop feeding items.</p></Panel>;
}
export function CircleTool() {
  const [diameter, sd] = useState("21"), [filled, sf] = useState("outline");
  const result = calculate(() => circleGrid(n(diameter), filled === "filled"));
  return <Panel><Fields><NumberField label="Diameter in blocks" value={diameter} onChange={sd} min={1} max={256} /><Choice label="Shape" value={filled} onChange={sf} options={[{ value: "outline", label: "Circle outline" }, { value: "filled", label: "Filled disk" }]} /></Fields><Result error={result.error}>{result.value && <><Metrics rows={[["Blocks", result.value.count], ["Diameter", result.value.grid.length]]} /><div className="mt-4 overflow-auto"><div style={{ width: Math.max(240, result.value.grid.length * 4) }} dangerouslySetInnerHTML={{ __html: circleSvg(result.value.grid) }} /></div><div className="mt-4 flex flex-wrap gap-2"><Download value={circleSvg(result.value.grid)} name={`minecraft-circle-${diameter}.svg`} mime="image/svg+xml">Download SVG</Download><Download value={result.value.grid.map(row => row.map(cell => cell ? "1" : "0").join(",")).join("\n")} name={`minecraft-circle-${diameter}.csv`} mime="text/csv">Download block grid</Download><Button variant="outline" onClick={() => { const grid = result.value!.grid; const canvas = document.createElement("canvas"); canvas.width = canvas.height = grid.length * 10; const context = canvas.getContext("2d"); if (!context) return; context.fillStyle = "white"; context.fillRect(0, 0, canvas.width, canvas.height); context.fillStyle = "#166534"; grid.forEach((row, z) => row.forEach((cell, x) => { if (cell) context.fillRect(x * 10, z * 10, 10, 10); })); const link = document.createElement("a"); link.download = `minecraft-circle-${diameter}.png`; link.href = canvas.toDataURL("image/png"); link.click(); }}>Download PNG</Button></div></>}</Result><p className="text-sm text-muted">Filled blocks have centers within the radius. An outline keeps the disk's outside blocks using four-direction neighbors. Odd diameters center on a block; even diameters center between blocks. All exports use the displayed grid.</p></Panel>;
}
export function XpTool() {
  const [level, sl] = useState("20"), [progress, sp] = useState("0"), [target, st] = useState("30");
  const result = calculate(() => xpPlan(n(level), n(progress), n(target)));
  return <Panel><Fields><NumberField label="Current level" value={level} onChange={sl} min={0} max={9999} /><NumberField label="Progress toward next level (%)" value={progress} onChange={sp} min={0} max={100} step={0.1} /><NumberField label="Target level" value={target} onChange={st} min={0} max={10000} /></Fields><Result error={result.error}>{result.value && <Metrics rows={[["Experience points needed", result.value.needed], ["Estimated experience held", result.value.currentXp], ["Experience at target level", result.value.targetXp], ["Points in the current level", result.value.nextLevelXp]]} />}</Result><p className="text-sm text-muted">The experience bar is a fraction of the current level, whose cost increases at higher levels. Percentage input rounds accumulated points down. Spending levels at an anvil is a different calculation.</p></Panel>;
}
export function BeaconTool() {
  const [layers, sl] = useState("4"), [width, sw] = useState("1"), [depth, sd] = useState("1");
  const result = calculate(() => beaconPlan(n(layers), n(width), n(depth)));
  return <Panel><Fields><NumberField label="Pyramid layers" value={layers} onChange={sl} min={1} max={4} /><NumberField label="Adjacent beacon columns" value={width} onChange={sw} min={1} max={6} /><NumberField label="Adjacent beacon rows" value={depth} onChange={sd} min={1} max={6} /></Fields><Result error={result.error}>{result.value && <><Metrics rows={[["Mineral blocks", result.value.blocks], ["Ingots or gems for those blocks", result.value.mineralItems], ["Beacons", result.value.beaconCount], ["Glass for beacons", result.value.glass], ["Obsidian for beacons", result.value.obsidian], ["Nether stars", result.value.netherStars]]} /><p className="mt-4 text-sm">Layer counts, top to bottom: {result.value.layerCounts.map(format).join(", ")}.</p></>}</Result><p className="text-sm text-muted">This is a solid rectangular pyramid beneath an adjacent beacon grid. Mix permitted iron, gold, emerald, diamond, and netherite blocks. Activation payment is separate from construction materials, and beacons need a clear sky beam.</p></Panel>;
}
export function BuildingTool() {
  const [shape, ss] = useState("room"), [width, sw] = useState("9"), [depth, sd] = useState("9"), [height, sh] = useState("5"), [openings, so] = useState("0");
  const result = calculate(() => buildingPlan(shape as "box" | "room" | "walls" | "floor" | "cylinder", n(width), n(depth), n(height), n(openings)));
  return <Panel><Fields><Choice label="Design" value={shape} onChange={ss} options={[{ value: "room", label: "Closed room, one-block shell" }, { value: "box", label: "Solid box" }, { value: "walls", label: "Walls without floor or roof" }, { value: "floor", label: "Single-layer floor" }, { value: "cylinder", label: "Circular wall without caps" }]} /><NumberField label={shape === "cylinder" ? "Outside diameter" : "Outside width"} value={width} onChange={sw} min={1} max={shape === "cylinder" ? 256 : 512} />{shape !== "cylinder" && <NumberField label="Outside depth" value={depth} onChange={sd} min={1} max={512} />}{shape !== "floor" && <NumberField label="Outside height" value={height} onChange={sh} min={1} max={512} />}<NumberField label="Blocks removed for openings" value={openings} onChange={so} min={0} /></Fields><Result error={result.error}>{result.value && <Metrics rows={[["Building blocks", result.value.blocks], ["Full stacks of 64", result.value.stacks64], ["Remaining blocks", result.value.remaining64]]} />}</Result><p className="text-sm text-muted">Dimensions include the outside walls. Corners count once. A room includes its floor and roof; circular walls use the pixel circle generator's outline. Subtract the exact number of blocks removed for windows or doors. Use the crafting planner to convert this total into recipe materials.</p></Panel>;
}
export function StrongholdTool() {
  const [ax, sax] = useState("0"), [az, saz] = useState("0"), [ay, say] = useState("-45"), [bx, sbx] = useState("1000"), [bz, sbz] = useState("0"), [by, sby] = useState("45"), [error, se] = useState("0.25");
  const result = calculate(() => triangulate({ x: n(ax), z: n(az), yaw: n(ay) }, { x: n(bx), z: n(bz), yaw: n(by) }, n(error)));
  return <Panel><Fields><NumberField label="First observation X" value={ax} onChange={sax} /><NumberField label="First observation Z" value={az} onChange={saz} /><NumberField label="First yaw in degrees" value={ay} onChange={say} min={-180} max={180} step={0.01} /><NumberField label="Second observation X" value={bx} onChange={sbx} /><NumberField label="Second observation Z" value={bz} onChange={sbz} /><NumberField label="Second yaw in degrees" value={by} onChange={sby} min={-180} max={180} step={0.01} /><NumberField label="Possible bearing error (+/- degrees)" value={error} onChange={se} min={0.01} max={5} step={0.01} /></Fields><Result error={result.error}>{result.value && <><Metrics rows={[["Estimated X", result.value.x], ["Estimated Z", result.value.z], ["Distance from first observation", result.value.distanceA], ["Distance from second observation", result.value.distanceB]]} />{result.value.uncertainty ? <p className="mt-4 text-sm">Bearing-only uncertainty bounds: X {format(result.value.uncertainty.minX)} to {format(result.value.uncertainty.maxX)}, Z {format(result.value.uncertainty.minZ)} to {format(result.value.uncertainty.maxZ)}.</p> : <p role="alert" className="mt-4 text-sm text-amber-700 dark:text-amber-300">Your error range includes unstable intersections. Take another observation farther to the side before travelling.</p>}</>}</Result><p className="text-sm text-muted">Java yaw is 0 toward positive Z, 90 toward negative X, and -90 toward positive X. Face along each Eye of Ender's horizontal flight and record the throw position. Both throws must target the same stronghold. This estimates a horizontal intersection, not portal-room coordinates or depth. On Bedrock you must measure bearings in this convention yourself.</p></Panel>;
}
