import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";
import { createClient } from "@supabase/supabase-js";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const DEFAULT_AUTHOR_ID = "4fc99a58-83da-46f6-9621-7816e36b4088";

const args = new Set(process.argv.slice(2));
const dryRun = args.has("--dry-run");
const skipSync = args.has("--skip-sync");

function isLocalSupabaseUrl(value: string | undefined): boolean {
  if (!value) return false;
  try {
    const host = new URL(value).hostname;
    return host === "localhost" || host === "127.0.0.1" || host === "::1";
  } catch {
    return false;
  }
}

function readEnvFile(filename: string): Record<string, string> {
  const envPath = path.join(repoRoot, filename);
  if (!fs.existsSync(envPath)) return {};
  const lines = fs.readFileSync(envPath, "utf8").split("\n");
  const out: Record<string, string> = {};
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq <= 0) continue;
    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }
    out[key] = value;
  }
  return out;
}

function writeEnvFile(filename: string, entries: Record<string, string>) {
  const lines = [
    `# ${filename} — generated by npm run setup:content-agent`,
    `# Production overlap checks and publish scripts read this file with NODE_ENV=production.`,
    "",
  ];
  for (const [key, value] of Object.entries(entries)) {
    lines.push(`${key}=${value}`);
  }
  lines.push("");
  const envPath = path.join(repoRoot, filename);
  if (dryRun) {
    console.log(`Would write ${filename}:\n${lines.join("\n")}`);
    return;
  }
  fs.writeFileSync(envPath, lines.join("\n"), "utf8");
  console.log(`Wrote ${filename}`);
}

function upsertLocalEnvLocalKeys(keys: Record<string, string>) {
  const envPath = path.join(repoRoot, ".env.local");
  if (!fs.existsSync(envPath)) {
    throw new Error("Missing .env.local. Bootstrap local Supabase and copy keys from npm run supabase:status:env first.");
  }
  let content = fs.readFileSync(envPath, "utf8");
  for (const [key, value] of Object.entries(keys)) {
    const pattern = new RegExp(`^${key}=.*$`, "m");
    if (pattern.test(content)) continue;
    content = content.trimEnd() + `\n${key}=${value}\n`;
    console.log(`Added ${key} to .env.local`);
  }
  if (!dryRun) fs.writeFileSync(envPath, content, "utf8");
}

function resolveProdCredentials(): Record<string, string> | null {
  const fromSecrets = {
    SUPABASE_URL: process.env.BLOXODES_PROD_SUPABASE_URL?.trim() ?? "",
    SUPABASE_ANON_KEY: process.env.BLOXODES_PROD_SUPABASE_ANON_KEY?.trim() ?? "",
    SUPABASE_SERVICE_ROLE: process.env.BLOXODES_PROD_SUPABASE_SERVICE_ROLE?.trim() ?? "",
  };

  if (fromSecrets.SUPABASE_URL && fromSecrets.SUPABASE_SERVICE_ROLE) {
    return {
      SUPABASE_URL: fromSecrets.SUPABASE_URL,
      SUPABASE_ANON_KEY: fromSecrets.SUPABASE_ANON_KEY,
      SUPABASE_SERVICE_ROLE: fromSecrets.SUPABASE_SERVICE_ROLE,
      SUPABASE_MEDIA_PUBLIC_URL:
        process.env.BLOXODES_PROD_SUPABASE_MEDIA_PUBLIC_URL?.trim() || "https://media.bloxodes.com",
      SUPABASE_MEDIA_BUCKET: process.env.BLOXODES_PROD_SUPABASE_MEDIA_BUCKET?.trim() || "bloxodes-media",
      NEXT_PUBLIC_SITE_URL: process.env.BLOXODES_PROD_SITE_URL?.trim() || "https://bloxodes.com",
      SITE_URL: process.env.BLOXODES_PROD_SITE_URL?.trim() || "https://bloxodes.com",
    };
  }

  const existing = readEnvFile(".env");
  if (existing.SUPABASE_URL && existing.SUPABASE_SERVICE_ROLE && !isLocalSupabaseUrl(existing.SUPABASE_URL)) {
    console.log("Using existing .env production credentials.");
    return existing as Record<string, string>;
  }

  return null;
}

async function verifyProdRead(prod: Record<string, string>): Promise<void> {
  const client = createClient(prod.SUPABASE_URL, prod.SUPABASE_SERVICE_ROLE, {
    auth: { autoRefreshToken: false, persistSession: false },
  });
  const { count, error } = await client.from("articles").select("*", { count: "exact", head: true });
  if (error) throw new Error(`Production Supabase read failed: ${error.message}`);
  console.log(`Production read OK (articles count: ${count ?? "unknown"})`);
}

async function seedLocalAuthor(localUrl: string, localKey: string): Promise<void> {
  const client = createClient(localUrl, localKey, {
    auth: { autoRefreshToken: false, persistSession: false },
  });
  const { data: existing, error: readError } = await client
    .from("authors")
    .select("id")
    .eq("id", DEFAULT_AUTHOR_ID)
    .maybeSingle();
  if (readError) throw new Error(`Failed to read local authors: ${readError.message}`);
  if (existing) {
    console.log("Local default author already present.");
    return;
  }
  if (dryRun) {
    console.log("Would seed local default author for article import.");
    return;
  }
  const { error } = await client.from("authors").insert({
    id: DEFAULT_AUTHOR_ID,
    name: "Bloxodes",
    slug: "bloxodes",
    bio_md: "Local dev author for content-agent verification.",
  });
  if (error) throw new Error(`Failed to seed local author: ${error.message}`);
  console.log("Seeded local default author for article import.");
}

function runSync(): void {
  if (dryRun) {
    console.log("Would run npm run sync:local-public-sample");
    return;
  }
  const result = spawnSync("npm", ["run", "sync:local-public-sample"], {
    cwd: repoRoot,
    env: process.env,
    stdio: "inherit",
  });
  if (result.status !== 0) {
    throw new Error("sync:local-public-sample failed");
  }
}

async function main() {
  const localEnv = readEnvFile(".env.local");
  const localUrl = localEnv.SUPABASE_URL;
  const localKey = localEnv.SUPABASE_SERVICE_ROLE;
  if (!localUrl || !localKey) {
    throw new Error(".env.local must define SUPABASE_URL and SUPABASE_SERVICE_ROLE (local stack).");
  }
  if (!isLocalSupabaseUrl(localUrl)) {
    throw new Error(`.env.local SUPABASE_URL is not local (${localUrl}).`);
  }

  upsertLocalEnvLocalKeys({
    SUPABASE_MEDIA_BUCKET: localEnv.SUPABASE_MEDIA_BUCKET || "bloxodes-media",
  });

  const prod = resolveProdCredentials();
  if (!prod) {
    throw new Error(
      "Missing production credentials. Set Cursor Cloud secrets BLOXODES_PROD_SUPABASE_URL, " +
        "BLOXODES_PROD_SUPABASE_ANON_KEY, and BLOXODES_PROD_SUPABASE_SERVICE_ROLE, then rerun " +
        "npm run setup:content-agent — or copy .env.production.example to .env manually."
    );
  }

  if (isLocalSupabaseUrl(prod.SUPABASE_URL)) {
    throw new Error("Production SUPABASE_URL must not be local.");
  }

  writeEnvFile(".env", prod);
  await verifyProdRead(prod);
  await seedLocalAuthor(localUrl, localKey);

  if (!skipSync) {
    console.log("Syncing production public sample into local Supabase...");
    runSync();
  } else {
    console.log("Skipped sync:local-public-sample (--skip-sync).");
  }

  console.log("Content-agent env setup complete.");
  console.log("  Prod overlap: NODE_ENV=production npx tsx -e \"import './scripts/shared/load-env'; ...\"");
  console.log("  Local verify: npm run dev:local + verify:*-final scripts");
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
