update public.catalog_pages as cp
set
  intro_md = content.intro_md,
  wiki_md = content.wiki_md
from (
  values
    (
      'the-forge-races',
      $intro$Races are The Forge's version of classes, and they matter much more than they first appear. You do not choose one directly when you start. Instead, you roll into a race, and that roll shapes your early damage, health, movement, luck, stamina efficiency, or utility depending on what you land. A strong race can smooth out early progression, while a weak one can make the same stretch of content feel slower and more expensive.

That is why rerolls matter so much. Current reroll options come through the shop, redeem codes, daily login rewards, events, and Robux purchases, so most players eventually face the same question: keep a decent race, or gamble for something stronger. Higher-tier races can dramatically improve mining, combat, or general account efficiency, but they are also much rarer, and burning rerolls blindly is one of the easiest ways to waste a useful resource.

Use this races catalog when you want a clear read on what each roll actually gives you. It brings together tiers, rarities, roll chances, and stat bonuses in one place, so you can tell the difference between a race that is merely usable, one that is ideal for farming, and one that is worth building around for the long haul.$intro$,
      $wiki$Races are The Forge's roll-based class system, shaping your starting stat profile before gear and upgrades do the rest. Each race changes damage, health, and movement speed, and the spread between common and high-tier rolls matters enough to change how comfortable early progression feels. Use the races catalog to compare tiers, rarities, roll chances, and stat bonuses before spending rerolls. It is the fastest way to see which races lean toward mining, which support safer combat, and which rare options are worth chasing for a long-term build.$wiki$
    ),
    (
      'the-forge-ores',
      $intro$Ores are the foundation of everything in The Forge. Every weapon, armor piece, and most meaningful crafting decisions start with what you mined and what you decided to keep. That is why ores are not just vendor loot. Each one has a rarity, a drop chance, a region, a multiplier, and often a trait that can influence how valuable it is in recipes. Once you move beyond the early game, those differences matter a lot because the wrong ore can drag down a forge result, while the right one can push a craft into something genuinely worth keeping.

The system gets deeper the farther you go. Ore quantity helps determine weight class, ore quality affects how strong the finished item can be, and special materials start to split into clear roles. Some are mostly stepping stones. Some are efficient sell materials. Some are premium ingredients you should almost never throw away without a plan. The current progression path also spreads ores across multiple islands and sub-areas, so location knowledge matters nearly as much as raw luck once you start targeting better recipes.

Use this ores catalog when you want to compare regions, traits, rock sources, multipliers, sell values, and rarity without jumping between scattered notes. It is built to help you answer the questions that matter most: what to mine next, what to save for forging, what to sell for gold, and which rare ores are strong enough to shape your next real upgrade.$intro$,
      $wiki$Ores sit at the center of The Forge's progression loop because they decide what you can forge and how strong the result can be. Region, rarity, drop chance, multiplier, sell price, trait, and rock source all matter, especially once you start saving premium materials for better weapons, armor, and pickaxes. Use the ores catalog to compare where each ore appears, what trait it can pass into crafted gear, and which materials are best sold versus saved. It is especially useful when you are planning a route through Stonewake's Cross, Forgotten Kingdom, Frostspire Expanse, and later areas.$wiki$
    ),
    (
      'the-forge-pickaxes',
      $intro$Pickaxes decide what kind of progress is even possible in The Forge. Mining power determines which rocks you can break, mining speed changes how quickly you can farm, and luck affects how often the game pays you back with better ores. Because every major gear upgrade begins with mining, your pickaxe is not just a tool. It is the gatekeeper for the next part of the game.

That is why pickaxe progression is one of the most important routes to plan well. Early upgrades come quickly, but the middle of the game is where a lot of players stall, especially when deciding whether to bridge through several smaller upgrades or save directly for a major jump. Current progression also spreads pickaxes across shops, quests, hidden rooms, and later-island objectives, so knowing where a pickaxe comes from matters just as much as knowing its stats.

Use this pickaxes catalog to compare power, speed, luck, rune slots, cost, and how each pickaxe is obtained. It is designed to help you map out practical upgrades across Stonewake's Cross, Forgotten Kingdom, Frostspire Expanse, Crimson Sakura, and special quest-gated content, so you can spend your gold and rare materials with a clear target instead of guessing.$intro$,
      $wiki$Pickaxes control more than mining speed in The Forge. Power gates which rocks you can break, luck affects how often rare ores appear, and extra slots help later builds scale better. Because every major progression jump depends on mining stronger materials, pickaxe upgrades shape the pace of the entire game. Use the pickaxes catalog to compare power, speed, luck, slots, costs, and where each pickaxe is found. It is a practical way to map out early, mid-game, and late-game upgrades before spending coins, keys, or rare ores on the wrong step.$wiki$
    ),
    (
      'the-forge-weapons',
      $intro$Weapons are where The Forge's mining loop turns into real combat power. You mine ore, choose a recipe path, run the forge, and end up with something that can either carry your account forward or waste a pile of good materials. Because the game has a wide spread of weapon classes with different damage, speed, range, pricing, and forge chances, choosing a weapon is never just about what looks coolest. It is about what fits your current resources and how you actually fight.

The forge itself adds another layer. Before crafting, you can check the percentage menu to see what you are likely to make, and doing that saves a lot of regret. Mixing ores can change the outcome depending on your primary material, and the weapon forge process runs through multiple minigames, with the Fast Forge gamepass currently skipping two of them. That means good weapon planning is part recipe knowledge, part material discipline, and part understanding how much risk you are taking with each attempt.

Use this weapons catalog to compare weapon classes, baseline stats, forge odds, and key differences between options before spending premium ore. It is meant for the moment when you need to decide whether to craft a short-term weapon, hold for a better recipe, or push toward a weapon that can carry you through the next stretch of harder content.$intro$,
      $wiki$Weapons are forged from the ores you mine, so they are where resource planning turns directly into combat power. Different weapon classes trade damage, attack speed, range, sell value, and forge chance, which means the best choice depends on both your build and the materials you can reliably farm. Use the weapons catalog to compare classes, core stats, and forge rates before you commit valuable ore to a recipe. It is most useful when you are deciding whether to push a cheaper weapon now or hold premium materials for a stronger upgrade later.$wiki$
    ),
    (
      'the-forge-armors',
      $intro$Armor is what keeps a promising run from turning into a wipe. In The Forge, stronger enemies hit hard enough that raw weapon damage is never the whole story. A good armor set lets you stay in dangerous areas longer, complete harder quests more safely, and survive the mistakes that tougher zones punish immediately. Since armor is split across helmets, chestplates, and leggings, gearing well means thinking in full-set terms instead of chasing one lucky piece.

The forge rules matter here too. Ore quantity affects the weight class of what you make, ore quality affects how strong the resulting stats can be, and the percentage menu is just as important for armor as it is for weapons. If you are using rare materials, you want to know what your likely outcomes are before committing them. That becomes even more important when you start deciding whether a set is only a stepping stone or something worth enhancing and holding for a long time.

Use this armors catalog to compare armor classes, slots, health values, base prices, and forge chances in one place. It is built to help you figure out which pieces are early-game filler, which sets stabilize difficult areas, and which ones deserve your best ore because they can carry you into the next serious progression wall.$intro$,
      $wiki$Armor determines how long you can stay in difficult zones and how safely you can finish harder quests, secret areas, and boss encounters. In The Forge, each set is split across helmets, chestplates, and leggings, and class, base health, sell value, and forge chance all matter when you are planning a durable build. Use the armors catalog to compare armor classes, slots, health values, and forging odds before you spend rare materials. It is a clean way to judge whether a set is a short-term bridge, a farming upgrade, or something worth enhancing for longer progression.$wiki$
    ),
    (
      'the-forge-runes',
      $intro$Runes are where a normal item starts becoming a real build piece. They drop from enemies, carry elemental or utility effects, and can add power that changes how a weapon, armor piece, or pickaxe actually performs once you have something worth investing in. Some runes support raw damage, some improve mining, some add status effects, and some are simply better than others for the amount of effort they take to farm.

They also come with an important restriction: runes are gear-specific. A pickaxe rune only belongs on a pickaxe, a weapon rune only belongs on a weapon, and the same logic applies across the system. That makes timing important. Carving a rune into weak temporary gear is often a waste, especially once enhancement and slot unlocks start becoming part of the decision. By the mid and late game, rune planning matters almost as much as your base forge materials.

Use this runes catalog to compare elements, rarities, effects, and primary enemy drops before you start carving anything. It gives you a clean way to see which runes are worth farming now, which ones are better saved for stronger gear, and which drops are tied to the exact enemies and areas you should be prioritizing next.$intro$,
      $wiki$Runes add a second layer of build-making after basic forging. They bring elemental identity, special effects, and gear-specific bonuses that can change how a weapon, armor piece, or pickaxe performs once your base item is worth keeping. Because rune slots become more important deeper into the game, it helps to know what to farm before you start carving. Use the runes catalog to compare elements, rarities, effects, and primary drops in one place. It is the easiest way to plan which runes support mining, which improve combat, and which are worth holding for better gear instead of using immediately.$wiki$
    ),
    (
      'the-forge-quests',
      $intro$Quests in The Forge are not filler content. They are one of the main ways the game quietly controls progression. Some teach the basics of mining, forging, and upgrading. Others unlock rooms, keys, pickaxes, side areas, and major character chains that lead to much stronger rewards. If you ignore quests for too long, it is easy to end up overfarming old content while the real path forward is sitting behind an NPC you forgot to revisit.

That matters more as the world opens up. Early quests around Sensei Moro help move players through the opening game, but later chains tied to characters like Captain Rowan, Bard, Raven, Goblin King, Bjorn, Monke, Tomo, Isaac, and Skal start connecting directly to secrets, doors, and important progression checkpoints. Current quest routes also include notable unlocks like the Lost Guitar reward path for the Unknown Key and Demon Skal's late-game chain for the Demonite Key.

Use this quests catalog to track quests by world, NPC, status, and objective list so you always know what the next meaningful task actually is. It is meant to help you move with purpose, especially when you are trying to unlock a room, finish a character chain, or figure out which quest reward matters most for the build you are pushing toward.$intro$,
      $wiki$Quests are a real progression system in The Forge, not just side tasks for extra rewards. Important questlines can unlock keys, rooms, NPC interactions, blueprints, and access to better gear, which means your next milestone is often tied to a specific objective instead of raw grinding alone. Use the quests catalog to track quests by world, NPC, status, and listed objectives. It is especially helpful when you need to know which quest unlocks your next area, which character advances a chain, or which reward is worth prioritizing first.$wiki$
    ),
    (
      'the-forge-npcs',
      $intro$NPCs are how The Forge organizes almost every important system without spelling it out too loudly. If you need a pickaxe, a potion, a reroll, a way to sell extra gear, a quest chain, an enhancement upgrade, a rune service, or a hidden progression trigger, there is usually one specific character tied to that job. Knowing the right name and the right location saves a surprising amount of time once the game starts sending you across islands and sub-areas.

The early-game cast already matters a lot. Miner Fred handles key pickaxe progression, Maria is central for potion shopping, the Wizard is tied to race rerolls and travel utility, and the Enhancer and Runemaker become more important the longer you play. From there the list grows fast. NPCs like Goblin King, Goblin Lord, Raven, localModuled, Zarall, Fungi, Captain Rowan, and Bard all connect to later systems, keys, blueprints, or special quest branches that can change what content opens next.

Use this NPC catalog when you need a quick answer to the most practical question in the game: who do I need to talk to right now? It brings together roles, areas, and locations so you can move directly to the right merchant, quest giver, or progression NPC instead of running in circles trying to remember where the game parked them.$intro$,
      $wiki$NPCs are the connective tissue between most of The Forge's systems. Shops, selling, race rerolls, potions, enhancement, rune work, and major questlines all run through specific characters, so knowing who handles what saves a lot of wandering once the world starts to open up. Use the NPC catalog to compare roles, areas, and locations at a glance. It is useful when you need to find the right merchant or quest giver quickly, especially during progression chains that bounce between crafters, vendors, and hidden story-related characters.$wiki$
    ),
    (
      'the-forge-locations',
      $intro$Locations are not just backdrop in The Forge. Every area changes what you can mine, what you can fight, which NPCs you can reach, and which secrets or quest steps become available. That means map knowledge turns into progression knowledge very quickly. If you know what a place contains, you know what you can reasonably farm there and whether you are actually ready for it.

The current game now stretches across four main islands, with Stonewake's Cross opening the path, then branching into later regions like Forgotten Kingdom, Frostspire Expanse, and Crimson Sakura Isles. From there, sub-areas and secret locations add another layer: caves, camps, quest rooms, towers, hidden roofs, the Raven Cave, and harder spaces like Volcanic Depths or The Peak all push the game in different directions. Some locations are there for steady farming. Others are progress gates disguised as exploration.

Use this locations catalog as a clean map-style reference for major areas, location types, and why each place matters. It is especially helpful when you are routing quests, looking for a specific NPC, planning a farming loop, or trying to understand which location is actually worth your time before you spend the next hour running across the wrong island.$intro$,
      $wiki$Locations do more than provide scenery in The Forge. Each area shapes what ores you can mine, which enemies you face, which NPCs appear, and what secrets or quest steps become available. As the game moves from early worlds into harder regions and hidden spaces, location knowledge becomes part of progression planning. Use the locations catalog as a map-style reference for major areas, location types, and why each place matters. It helps when you are routing quests, looking for system NPCs, or figuring out where the next meaningful mining or combat step begins.$wiki$
    ),
    (
      'the-forge-enemies',
      $intro$Enemies are one of the clearest reality checks in The Forge. You can think your build is ready for the next area, but the local enemy roster will tell you the truth almost immediately. Their health, damage, level, gold payout, and experience rewards determine whether a zone feels efficient, frustrating, or completely out of reach. As the game moves into stronger regions, enemies stop being background obstacles and start becoming the system that decides whether your current gear is actually good enough.

They matter for more than survival too. Enemies are one of the main sources of essences, rune drops, and other valuable materials, which means combat farming is directly tied to progression. Some mobs are mainly useful for steady essence income. Others become priority targets because they can drop stronger runes, premium essences, or special ore rewards. By the time you are fighting through places like Frostspire, Raven Cave, The Peak, or Volcanic Depths, knowing what a zone drops is just as important as knowing how hard it hits.

Use this enemies catalog to compare enemy stats, areas, and rewards before you commit to a farming route. It is meant to help you see where difficulty spikes begin, which enemies are worth revisiting for materials, and whether your next stop should be a gold grind, an essence grind, or a straight progression push into harder content.$intro$,
      $wiki$Enemies are one of the main pressure checks in The Forge because they test whether your current gear can keep up with the area you want to farm. Their levels, health, damage, gold payouts, and experience rewards all change how efficient a zone feels, and tougher enemies also matter because they feed later upgrade systems through essence drops. Use the enemies catalog to compare enemy stats, areas, and rewards before you push into a harder region. It is a practical reference for planning farming routes, checking whether a zone is worth grinding, and seeing where combat progression starts to spike.$wiki$
    ),
    (
      'the-forge-essences',
      $intro$Essences are the reason enemy farming never really stops mattering in The Forge. They drop from mobs and bosses, come in several tiers, and are one of the main materials used at the Enhancer to strengthen your equipment. That makes them the bridge between combat and long-term gear progression. Mining gets you the base item. Essences help turn that item into something strong enough to keep.

The difference between tiers matters a lot. Tiny and Small Essence are early progression fuel. Medium and Large Essence help carry the awkward middle stretch. Greater, Superior, Epic, and Legendary Essence are where the stakes rise, because those stacks start getting tied to stronger weapons, better armor, and upgrades you do not want to waste on replaceable gear. Current guides also connect essences to slot planning, since enhancing gear far enough is part of preparing items for rune use.

Use this essences catalog to compare tiers, descriptions, and progression value before you spend a single stack. It is designed to help you answer the real question behind every upgrade decision: should this gear be enhanced now, should these essences be saved for a stronger item, or is this the piece that deserves a serious investment because it is finally good enough to build around?$intro$,
      $wiki$Essences link combat progression to gear progression. They drop from enemies, come in multiple tiers, and are used to strengthen equipment through enhancement, making them one of the main resources that separates temporary gear from items worth investing in for the long run. Use the essences catalog to compare tiers and descriptions so you can judge which stacks are routine upgrade fuel and which ones are better saved for stronger equipment. It is especially useful when you are deciding whether to enhance now, wait for a better weapon, or prepare gear for rune slots.$wiki$
    ),
    (
      'the-forge-skills',
      $intro$Skills are one of The Forge's most underrated progression systems because they reward the way you naturally play over time. They are tied to achievements and milestones, then equipped through the Achievements menu as passive boosts. That means your account can quietly get stronger while you mine, forge, explore, kill enemies, level up, or apply runes, even if you are not farming a single headline item at that moment.

The system is especially strong once you understand what each skill is pushing you toward. Current skill lines reward things like forging weapons, forging armor, mining rocks, killing bosses, exploring areas, spending time in the game, and applying runes. In return, they boost stats such as attack speed, health, mine power, damage, luck, stamina, movement speed, XP gain, and more. Only one skill boost can be equipped at a time, so choosing the right one for your current goal actually matters.

Use this skills catalog to compare each skill's boost, requirement, and summary in a way that is easy to act on. It is built for players who want to know which achievement path helps their current build most, which passive is best for mining or combat, and what long-term milestones are worth keeping in mind while they grind.$intro$,
      $wiki$Skills reward long-term play patterns in The Forge by tying permanent boosts to specific achievements and milestones. Mining, fighting, forging, and other repeated actions can all feed into these bonuses, which means your account becomes more efficient over time even when you are not chasing a single new item. Use the skills catalog to compare each boost, the requirement tied to it, and the summary of what it improves. It is a good reference when you want to know which achievements support your current build and which passive upgrades are worth targeting next.$wiki$
    ),
    (
      'the-forge-potions',
      $intro$Potions are The Forge's cleanest short-term power spike. Instead of changing your whole build, they give you a focused boost for the exact session you are about to play. That can mean a safer fight, a faster mining route, better luck during a rare-ore farm, or a small edge that turns an annoying quest step into something manageable. Used casually, they are convenient. Used at the right moment, they can save a lot of time.

The current potion pool covers several useful needs: healing, damage, movement, mining speed, and luck. Most players meet these through Maria's Shop, which makes potions one of the easiest systems to understand but also one of the easiest to waste. Burning a strong consumable during random wandering is rarely worth it. Saving it for a harder zone, a focused ore route, or a risky progression window is where the value really shows up.

Use this potions catalog to compare costs, durations, and effects before you spend your gold. It is meant to help you choose the right consumable for the job, whether that job is surviving a rough fight, squeezing more value out of a farming run, or stacking short-term efficiency for a specific goal you want to finish now.$intro$,
      $wiki$Potions are short-duration boosts that help you get more value out of specific sessions instead of day-to-day wandering. Depending on the type, they can support mining, damage, speed, luck, or survival, so timing matters almost as much as the item itself. Use the potions catalog to compare costs and effects before you buy or spend them. It is most useful when you are preparing for a difficult zone, a focused ore farm, or a short progression push where temporary efficiency matters more than raw inventory value.$wiki$
    ),
    (
      'the-forge-totems',
      $intro$Totems are the premium version of a planned farming session in The Forge. They are short-duration boosts, usually around five minutes, but those minutes can be extremely valuable when you line them up with the right activity. A good totem can turn a routine route into a serious ore hunt, a combat session into a fast leveling push, or a difficult progression wall into something much more manageable.

Each totem serves a different purpose. Current options focus on luck, damage, health sustain, XP gain, or mining performance, so choosing one is really choosing what kind of session you want to optimize. That is why timing matters. A totem used at random is just a nice bonus. A totem used during a 2x luck weekend, a rare-material grind, a high-XP route, or a hard push through stronger enemies can completely change the value you get out of those five minutes.

Use this totems catalog to compare costs and effects before you spend one. It is designed to help you decide which totem fits the grind you are planning, when a premium boost is actually worth using, and which sessions deserve the extra push because the rewards on the other side are finally good enough to justify it.$intro$,
      $wiki$Totems are temporary boosters designed for planned grind windows, especially when you want better results from mining or combat over a short span. They are often most valuable when stacked with specific goals, such as rare ore hunting, leveling, or event-driven luck sessions. Use the totems catalog to compare costs and effects before using one. It gives you a quick way to decide which totems are best for farming, which are worth saving for stronger sessions, and when a temporary boost is actually worth the price.$wiki$
    ),
    (
      'the-forge-blueprints',
      $intro$Blueprints are your crafting roadmap for special gear in The Forge. When you want a specific weapon or armor piece, the blueprint tells you whether that target is actually obtainable, where it comes from, and what progression path leads to it. That matters because many of the most interesting gear goals are not simple shop purchases. They are tied to events, questlines, limited content, hidden vendors, or side systems that are easy to miss if you only focus on raw materials.

Current blueprint routes already show how varied the system can be. Some are tied to event content like Hidden Maze rewards. Some are connected to stores such as Fungi's shop. Others can point toward quests, rarer sources, or availability limits that change whether a craft is part of your current plan or something you simply cannot chase right now. Without that context, it is easy to waste time farming ingredients for a target you do not yet have access to.

Use this blueprints catalog to compare item types, sources, availability, and acquisition notes before you commit to any big forge goal. It is built to answer the question that matters most when you set your sights on a late-game weapon or armor piece: can I actually get this now, and if not, what part of the game do I need to clear first?$intro$,
      $wiki$Blueprints are the planning layer behind many of The Forge's best craft targets. They show what special weapon and armor recipes exist, where they come from, and whether they are currently obtainable, which matters a lot for event gear, quest rewards, and limited progression paths. Use the blueprints catalog to compare item types, sources, availability, and how to get each blueprint. It is the cleanest way to see whether a weapon or armor goal is tied to a questline, a shop, an event, or content that is no longer available.$wiki$
    )
) as content(code, intro_md, wiki_md)
where cp.code = content.code;
