import type { GameCollectionGroup } from "../types";

export const bloxFruitsCollectionGroup = {
    gameSlug: "blox-fruits",
    gameName: "Blox Fruits",
    universeId: 994732206,
    dataDir: "Blox Fruits",
    universeNames: ["Blox Fruits"],
    collections: [
      "abilities",
      "accessories",
      "aura-stages",
      "aura-visuals",
      "boats",
      "bosses",
      "enemies",
      "fighting-styles",
      "fruits",
      "guns",
      "instinct-levels",
      "locations",
      "materials",
      "npcs",
      "quests",
      "races",
      "sea-events",
      "special-titles",
      "swords",
      "title-colors",
      "titles",
      "fish",
      "fishing-rods",
      "baits",
      "potions",
      "trinkets",
      "scrolls",
      "enchantments",
      "aura-skins",
      "fruit-skins",
      "raids",
      "crafting-recipes",
      "currencies",
      "stats",
      "quest-items"
    ]
  } satisfies GameCollectionGroup;
