import "server-only";
import { createGameReader } from "./shared-game-reader";
export type { SharedGameGame as GtaGame } from "./shared-game-reader";
export type { SharedGameWikiPage as GtaWikiPage } from "./shared-game-reader";
export type { SharedGameWikiListEntry as GtaWikiListEntry } from "./shared-game-reader";
export type { SharedGameWikiCollectionPage as GtaWikiCollectionPage } from "./shared-game-reader";
export type { SharedGameCollectionDatasetDocument as GtaCollectionDatasetDocument } from "./shared-game-reader";
export type { PublishedSharedGameCollectionRuntime as PublishedGtaCollectionRuntime } from "./shared-game-reader";
const reader = createGameReader("gta");
export const buildGtaWikiPath = reader.buildSharedGameWikiPath;
export const buildGtaCollectionPath = reader.buildSharedGameCollectionPath;
export const resolveGtaWikiCoverImage = reader.resolveSharedGameWikiCoverImage;
export const resolveGtaWikiThumbnailImage = reader.resolveSharedGameWikiThumbnailImage;
export const listPublishedGtaGames = reader.listPublishedSharedGameGames;
export const getGtaGameBySlug = reader.getSharedGameGameBySlug;
export const listPublishedGtaWikiPages = reader.listPublishedSharedGameWikiPages;
export const getGtaWikiPageBySlug = reader.getSharedGameWikiPageBySlug;
export const getGtaWikiCollectionPageByPath = reader.getSharedGameWikiCollectionPageByPath;
export const listPublishedGtaWikiCollectionsByWikiSlug = reader.listPublishedSharedGameWikiCollectionsByWikiSlug;
export const listPublishedGtaWikiCollections = reader.listPublishedSharedGameWikiCollections;
export const listPublishedGtaWikiCollectionImageUrls = reader.listPublishedSharedGameWikiCollectionImageUrls;
export const getPublishedGtaWikiCollectionRuntime = reader.getPublishedSharedGameWikiCollectionRuntime;
