import "server-only";
import { createGameReader } from "./shared-game-reader";
export type { SharedGameGame as RedDeadGame } from "./shared-game-reader";
export type { SharedGameWikiPage as RedDeadWikiPage } from "./shared-game-reader";
export type { SharedGameWikiListEntry as RedDeadWikiListEntry } from "./shared-game-reader";
export type { SharedGameWikiCollectionPage as RedDeadWikiCollectionPage } from "./shared-game-reader";
export type { SharedGameCollectionDatasetDocument as RedDeadCollectionDatasetDocument } from "./shared-game-reader";
export type { PublishedSharedGameCollectionRuntime as PublishedRedDeadCollectionRuntime } from "./shared-game-reader";
const reader = createGameReader("red-dead");
export const buildRedDeadWikiPath = reader.buildSharedGameWikiPath;
export const buildRedDeadCollectionPath = reader.buildSharedGameCollectionPath;
export const resolveRedDeadWikiCoverImage = reader.resolveSharedGameWikiCoverImage;
export const resolveRedDeadWikiThumbnailImage = reader.resolveSharedGameWikiThumbnailImage;
export const listPublishedRedDeadGames = reader.listPublishedSharedGameGames;
export const getRedDeadGameBySlug = reader.getSharedGameGameBySlug;
export const listPublishedRedDeadWikiPages = reader.listPublishedSharedGameWikiPages;
export const getRedDeadWikiPageBySlug = reader.getSharedGameWikiPageBySlug;
export const getRedDeadWikiCollectionPageByPath = reader.getSharedGameWikiCollectionPageByPath;
export const listPublishedRedDeadWikiCollectionsByWikiSlug = reader.listPublishedSharedGameWikiCollectionsByWikiSlug;
export const listPublishedRedDeadWikiCollections = reader.listPublishedSharedGameWikiCollections;
export const listPublishedRedDeadWikiCollectionImageUrls = reader.listPublishedSharedGameWikiCollectionImageUrls;
export const getPublishedRedDeadWikiCollectionRuntime = reader.getPublishedSharedGameWikiCollectionRuntime;
